using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using HotelModel.DB_Conn_DSL;
using System.Data.SqlClient;
using System.Data;
using System.Windows.Forms;

namespace HotelModel.Model
{
    public static class RoomLocationModel
    {
        /* Defining sql accessors: Snippet Autogenerated */
        private static DataSet _roomloc;
        private static SqlDataAdapter _roomloc_adapter;
        public static SqlDataAdapter roomloc_adapter { get { if ((roomloc == null) || true); return _roomloc_adapter; } }
        public static DataSet roomloc
        {
            get
            {
                if (_roomloc == null)
                {
                    _roomloc_adapter = (SqlDataAdapter)new SqlQuery("SELECT id_location, descr FROM BOBBY_TABLES.ROOM_LOCATION;").AsDataAdapter().Execute()["ReturnedValues"];
                    _roomloc = new DataSet();
                    _roomloc_adapter.Fill(_roomloc);
                }
                return _roomloc;
            }
        }

        public static void BindTo(ComboBox ctrl)
        {
            ctrl.DataSource = roomloc.Tables[0];
            ctrl.ValueMember = "id_location";
            ctrl.DisplayMember = "descr";
        }
    }
}
